image: python:3.7.3

pipelines:
  definitions:
    # Tests
    - step: &testaudit
        name: Audit test
        cache:
          - pip
        script:
          - pip install requests
          - bash cicd/run.bash
          - python audit.py
  default:
    - step: *testaudit